CREATE TABLE correntista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    documento VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    telefone VARCHAR(255),
    endereco VARCHAR(255)
);

CREATE TABLE conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255) NOT NULL UNIQUE,
    saldo DECIMAL(15, 2) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    tipo_conta VARCHAR(31) NOT NULL,
    correntista_id BIGINT NOT NULL,
    CONSTRAINT fk_conta_correntista FOREIGN KEY (correntista_id)
        REFERENCES correntista (id)
);

CREATE TABLE conta_corrente (
    id BIGINT PRIMARY KEY,
    limite DECIMAL(15, 2) NOT NULL,
    CONSTRAINT fk_conta_corrente_conta FOREIGN KEY (id)
        REFERENCES conta (id)
);

CREATE TABLE conta_poupanca (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_conta_poupanca_conta FOREIGN KEY (id)
        REFERENCES conta (id)
);

CREATE TABLE transacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL,
    valor DECIMAL(15, 2) NOT NULL,
    data TIMESTAMP NOT NULL,
    conta_origem_id BIGINT NOT NULL,
    CONSTRAINT fk_transacao_conta FOREIGN KEY (conta_origem_id)
        REFERENCES conta (id)
);
